language: java
jdk:
- oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: MUU3525zR0wBuPS9tlyiu3qgBerMcXHjbE5BHN8m9mPad8wehj8yxud8esHfvYqBErQ1h6wT9L5LvPfEnBLvlWXcK0e/wiRz00xhcuLK+mpbogI9hrNxXDA8GnfG57nrwaimmEvXGWDm3jtbqgIHm/564CivsBiddXoI6WuvhkpdrJqHOZxptzKVnLxLpApb+SxGp7yeIesAASjnEkErGhI1XoqjhI3o6z21zO8mCRBJq2nPcmZDFP+ZQdishIgy6pLGwhEfXENBVyVKesInt88n96ma9LPTAfhOgAa09lF3Pj1m5tMVdyER7cJnI8bghUoUxr+RMsGeB8WwPlZybpb1OaoQ9f2KqE6QgCiI+qwzlROCcOfCifp/JZNPKW6lL+f/ODeyQ7TR69bfgWKLPXPqYrjwp34l+Sbi6CHfYnsqbKMAofBrGIRS0DHC0ba5lKPGMbAZoBQHcCR0lSFfQAd4wnq+1wqko7/NTogvk6NRXIQz93VNt3SJ9X2NHjfQwlq1qjfA7ybtmCr74Dv9jKv8nk3GtXXWkf5y95LzDOPDKZrZCULbuteR2yN2uvY5gU0WH4Gu+csdremXzEF1YLPiz8Mj/v0fRZAy/bNv1YzJzSjN6obTfcrhRkcaUdspbNAFnZUTzCPixKXDbFAp2Pq5lFKFYFxf0PBD8LeDj2U=
  app: stagingshalarelax
