language: java
jdk:
- openjdk8
dist: trusty
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: sRerNLpjdF+/a7LbN0nKQLGd/9e8KJ93/RUO2AsnB/IjyU118IiRREjqH6Tb1vESx050UslCW1z4Bg23wobrioQO/XpQUbKupIm6B03mj4SJk84hnIQ9M7RHFEQaJq0BXJwoD8scDgdyTuJorziWKIvecrbADTshXWlLLaI3wc/QcBUIz8mRufaLS4QP8cM2TSv3V9LTSjqz1mJaxnTg5I0SA3dE2f1jwsYgfTngNVCllOSn5RYf+pJNZsQ1+h0Fvk6s0e72Bc9fo/M/cuYHl7jjbKDeCAejJ6kOmZslIF3KNXJFROaJbv1rV2FD8tq++ueYBw/EOF2Yv7L8rJsE6yDQKViiiQAf+9hoLdb8zZaR1M5+H/BdgTwYpzHCjXSRiE3ZfQYXgY3+n4ctgCXKjUl/mndAtJ4DM32KbYQSf+7+ZA3jAW5o8sieGe2ysJb//obgNYnKirADS2oDR8uMQyjsdot23sDfoxaC4DafkU3YftSG+OqckNtD9Ni+xEkunm4nWTY259zzhYZBeLytOaRvcGVmEDRx9QlIHsfP0PnuseMUhrmGzBMOD9rZc8vs0n9IwgP/1SlLf1JPl1qieewPogritkhsujC+O8IZTuXiaLLjrmWmX7udfwyQb+eCnYi8lcTRxC19uQY3y0eOF5LHMSjJD0kzKjeE2GJsE1s=
  app: stagingshalarelax