language: java
jdk:
- openjdk8
dist: trusty
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: j+necX4DrG232P9bOmkNiDlY4DqAue8OeXGe2IlIbrZj/06UwJOjM+xwvEZQuK5MvbryyWnRm32Z5SlXl38FYLlZVyfL5JFNY8XrTphOpv65zO1cTlaSW7btGa7CRukJZ3fzJXJQQnr+xmRwQhj4o4UDETMFDqcOTuEL6qXZNCtP3vdIKJ43w05O2Go89kAykcWPs4qCiIb3XEitoahdB+anMiLDC2pxxlQzwili2zk5Rfg5yU+Pmk5GdZkKYsPByVPT2w4cWegGMqMkNC6iQ4OXG+KUSvZL59pAp99Vmda/F0Yl8vtJ4Q79Sw1WWCKRnm3byi0cIHG7qu3xfyQdNBqCfXuEy5V0pjg+SmZuDH6/luMfqv17Rrg/kHaa9vOQo4iSQzFOLeOp7vKerjAXuakenQDsWFRnXUjrfo7OxoeUINdTAkRZEEYHVmNaztmiXVjNBmsJqvdd+N56tS0DuT7UBKXq6Z1w3tc5+B76JTVaeVLEmtvsVuJ6NwHddiVeExmcBy1XU+ivH0fuFWOLGLO4Bf+5ylT6xTO9gcZ2zWweWoVSbv8cDD6/xZKNHnjy/1zDsZcJ0GoJ7lTihi3hH0Q03jYsbhj8OlSvc2zVJ54BbR6bVDrfsx0tcFa10UFBpZJzo5e9YpXicRuI71VKYiDE8mlVaWBSIcleVbspxRI=
  app: stagingshalarelax
