language: java
jdk:
- oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: Iz6nvoOoReNu397zB5ox8w648MB30bAeZ6mkAS2pYj3m6hglUZvCCBGhUohBmOJwZINY3+Ucuuchs28lBrhULXVFaakcPodmb5cpxlAerRtZWzqHwy0fEAG121TWtvIgDlSxSH4Z+Bh2d7VCDoS5rndqNGKudCUdFBINc6+P7p9XiO66dXx6Gzt8awziODJdBVIDI/LKwpESnXQA3znEYrgzpqMyCCvihWUACsv18BbaT8XZ6+Q5JvoOSUZ9iGDTDqEkmWthkaTsooHxBUFUlItkYd1Q+C2B5bOwUvOketCTNkxec5Z6dcOJUYIr/dXcuUuOP6nQsseO5s6IYFluskAJslBBE7crjCw1FbRl0jD/2/C06Z2UJ1bvylXv+bQL+iPCgaSzOLU+UNBPrHbLe8MksS1AU5SmSYwpTwkX2ZItsCwNB15VSic+oaLF79IKtlsZRPyw7XCZDYlPycZ4XyLlTObus/9h9ZfxMkKNKAadMSFs0JI8ptISi7miMof9m2K3a9s29Fqd3gx3balYe+uohEXLxc8vXIvyMalTkChntG+DOJkKHgb+77DpUViGEYwMTG7l9DYJyfabZRBPWx5zVHweOxtq3GpWpCrboW75/YNgGrR7lrTeDZicn8ba+fvN6mIR2QfrsmAwtT7ny+0wvW/Zp1m6Fj6HX/e14ms=
  app: stagingshalarelax
