language: java
jdk:
- openjdk8
dist: trusty
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: pADRdswQmmbr/du3+4unOwT1AVXwn4W/dunRVO5v6ax+RYxihE2L+d8pkcJCrxKJ74P+Ga7YM5aNzBqZ+ksD1pzyY66VDocIUIpbmjPhh2NiSF2cAPnWV2hMPLVLUoC+rxnWhm1pMb6pTos6a7txXLDdA7qdmaa95+o1YVfD/X+xC+mtSaot3CxNEeOo+VKqWGk0fBwsLP3AdOD7QI7b1cQ7zhvQ1497/Nc/uFT1OlLXuuJLglV2RCZlcqRpSxLgDW9u7NXVWnNF/pb0QSWNY0L4fVWD7pkUCjKK45x/8D/WFJyp1IX/Y1EcfXJamOCHaVQVJ3j/F4MmCjZyop/C6KgWMySVMQBXCPIdtytSVaKNJwy6g67N+UHSjImwnxf9tcXSiUXFvUhBClZ/q/jhJC/Q5Yt36jnYlP7t4lwcZiCX2ddWkNBhWwaTr102fLy+BS2ShTc95fqT94lKQg37ofiy+M79LO7KB30tdy00NgysLOiyczD8GwfqTXNZHDushrfFXh5bcsWWUahPEpGCVkMWbSXqI0GqhkTuiN7pY9ZvdXL0QhOvfjB0TGDNLVLVUoFz1BSle/Zf9/xtYkuwTcOcL9ia7aV4ztr0MBVW/NYoqXh/wtx08I56mwi1dhQAcyWcckx6lDBuuo/HAxUXPWB4XjQjgW354ruJDGq4Ozo=
  app: stagingshalarelax
