language: java
jdk:
- oraclejdk8
- openjdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: hg4UnDM47j8XoXgH/IISP0QdUqO4HmCromLhWcNEkXP9+hGp/yXQXezqXxPXu1DXjvlcgvLx6y/bhJPJO6robjG3pbINZrxQe9pZamO97RsvbNRRnMZ/69/5KLFdODGBKPgNW4KldWLKO0OQcNjInMaEdw4mfC1b/Xmtfq8AwRgo7cOUqsDaPC2PHc34JCqNk8gKczCtxTTGB7CrphTnrE3XdXy9hbNB2v8HMfi+T3SId33vD78zddqYSZNHsBF+gqTkic+nibUIwIatPv+0iXerFW2eVirXcOsnBjTfGJM7E2L6Iy5puoqkYlQLyaQw6PffrilUTS2cf6EZ5dqx8JPAabpoLHx30/htvS/vRdVrg3Iac5PBxk/AxiupHI1ku8+4VgZQ4MpHWKA3FJRi/DzQbZCXHvrq/rtoG2sDl9Nefu9Wrg3rGM2w/E2UdHdn9FSytbK4N+lXy3nDMKUYkvRCtXpFiYEw5xJTAa+6OyeGFeLOcjYuficNlimf4mhOwaHKk5hWIN0+KL+y1CIJ0TtzZTpo0ZKGtjhIMbVGqyttreVPN0RkKYtz+EEeVw9pDFMARxD7Lh3WxbLOKAAKaTGJMd/9PzGqDE2EJc/vzaBlMets2KinAFaBdVi6kFEzPrwsOhuymtlQjZSpkaCO+PyqQdsktbgyQT5R2l0xNos=
  app: stagingshalarelax
