language: java
jdk:
- oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: T2zcDl2hE57XnFqPjiGDMxCiX5OiunCU+sxyDUiU63uNcCwGHa5GTcVsc2oUWS3z6RyIs5F+maXfYK+nHxCluJhOvHrQvizaoC761xxSnFL/PzogxnTX8889UzPK25eJJaAQSMbscZjvOAvbGfi9m5j81X/eUy1dz1oEY6aTeuoeGPVOrghBVj+ibjooWux9qilYlyM5shohCsHDRdktSi4XRhSQ/XPiy6NXgKGZvwC8/+oh11Ae+GTigMOFSCXcs2wuURjn4zBg7NUQ/I9Wfkuwadbtlvxy2EVG5spN74D7L/kq+bFMCwjaX23erhgBfrsc8RgdAX96JLAWvzxwleP1r1/IxOiEE7nU2HxDf8qC5oDPHcBIGcaEeDWUipuZqfMU5GsVyD7uu0ec3019kc6x6gwwv10ceWVe1SKVv5zIgn9ASN0Xt+IBGvqSQU4cY8UhzgACpLKl3G/J2W3hX4Bp1EJPkMEkYcu5UmUvhdznhF2+1u+alWLbc6VHQs5NRMRHOucOO20CdK3qA3YFY8rDdFJSXewspPUeWKHyxXVMPfMVmn0js61hY86+lIxzySHB2qR/a97xIE59UB17dkiAsntCIZML/YNleBmFM3s5M+6c3mtGxIGTMH2ZVomlwZWbQRJQHaNKbyhOTubZ4aH8KsETcERRMkaWo+viSME=
  app: stagingshalarelax
