language: java
jdk:
- openjdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: vGSP+JcvQTULS/vlDRZVrIhktGiwIc07j1KBaMiNNpnaTPdc7LRKJO09tK9VKAxFC5sqKn9rYqhq9D+Iouq4VXcifw+1wrFlGk3NVlt6FYEPiDpGzG6R8NC8J1TYYGeqKXfj/ylgkjEn30BluaPAHd8s4OgMg0ona1WLWC40Qw/K9WYHWgcR8grpezJCEblT8gUVr4DdQEgRHt2PgbNwQhTZzRKOtVzudJ6MzPruuZCtEN7IfcVL7YUN32Ui8OkE6LEif77F8MeJVH0Aea9EDbQ6tPt184dgZP0Rg8/mlEHmj8oRXRiMId1cRQ3Sjggh6Rh90p5YJg8fu0Bf/YFXkwb35qI9l1Eea80tC/joeNNoyMzJ7Rh4QEFxq6sd4rwYvFTU7FmmqyGT253IYdFdMA5cw/+cIDMLLN6gW58vWLBlaT9R9otprg1DkZYn0XqoKage5L1WArAvF+LH1xCjvXCSOPy0T6adza8GT66Y3ScwCvMnKkk/xZcc0b/Q0UT22f6AyLLypvhU0zWkd8loJ/6NXMHfgvm7Ilocd8SkNcaxXATTqw1uCG51r8YFUgfWqLpbS4O35d/T4bq2HYL7kWKJAlpAO5MvM02in/QWnXR/GVFzQ885Ryg6R+tcuXqzXGCdXk3deuUaXE4RgFhRfiA9D9zm1pZVfE7i6KWh1gk=
  app: stagingshalarelax
