language: java
jdk:
- openjdk8
dist: trusty
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: ZFLOQ8J2O2+yYhultJmKip2cUhKXTQnQ7ZtBkcrxGxXECaS9y6zN5lcmUV057cFTDy1LBZoiQ5uEE2/PsAZ0puQB9TIKjiasixAAdpkBkQrIY+PqiwEl+qjjeWOiyeXSUWWJcyLtd41tU2aNDlE2azzty9xRUPPQyMIhlw+1ZrQ7wV3BMR8cyBGNGfL801VeX76dYAF1uQvMmC2ncNg9+3yQpM1+VlK0J0G1rSOwWfP5vWli1+UmZrroetX7xZM12YJewXnbytrjljOHOnihi/QPyOuoyuqCvqMkuDGakzialSXJKwzBraUaHBqUWzfa9trzQBMqiSch62UuAAmWG+xvZSg/YbrhvyvY5+3iLEvdDDB6VI5Lo94N8kzYLBaIKXSxgYqUhBp7HwP4QEMf996T/aUktnY0a1Qr69RP7bsX32vBPIbDevnXq7iO9RWz3BqDDl53UDuqNt4YU+G4wUNYiclmqzqvW6MmwEd0Sl7TB6tV2PwGvl+RhGYrR/67GW4n0CaEzd0ay/ua2fyypzLlPIV5u0AnDcl+42KDuFUjdWMbxxohRWpx3OJu4KkUozj96NQtMwXtaXOh7M7C4LNnNmBt9qiBy0e/X3Uf7ocPzQ+hJyQ5lnSKSLX/D9pB7oLYmp+aQzc4AhxLOX/U/eeXqB17EcW6SZ0t7mLjHLY=
  app: stagingshalarelax
