language: java
jdk:
- oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: lKEO86Wq9RlCN89Fhprfo8dHUyDRrhUynCXvKbpeNoFWiJPHG7CCZh8PyTCd05ec5R9Zl6HrHUdEaWcho+cDk9pW5A2QrzdFnmyT5tufNlsGJ5NcjE0Zgs/Q85auNZ+UP0UKwYUZXkFTI7sym3JiA2jZKR0ehDYILPv0ekf6DcjNg01Swf/QMLzFPEwurBrl9f++DaaNXkLxOhlbE13Qh8aER2dTNoZMC6nFC8Nv5XoUJptFYN1pJ54JH/3tdI94ECZ5tOcrkj+Wg8wPbsVybXA+8BlmqblIBmsVMG8Th5A66gk9WDlexk7+p8nAqc55TJucJ+TkOTFEV4wOL/VMfi4qtgVTfWhEFt/E6CsmZoWaguqUKt1D4OkQUbZd8YEvt5MY+/FV8trr23veBq79AqQHQAj+y+vXzZuH6j34qGUcVru3ramqNcdzrcaOXumRt5B7M6TOGi7NCER5Pc/AUh44az++RkSzKAOWbCxI+cTm9jcT4MCFxYCZoMMt4/SRWjrJPIn3A09lwWRZ5VEoXfD1tXMp0FFX4VHVMwMjeDqCJA6zoq2uJ2bbbpw99j3hm22/pnxDHViNP9oySp3od7diQ0xKxl0OUSXYDzA8x7sKCwXhmBki5yVYXQ8iplShO6f/u37uDaQI8mbQiAs25XwGXCTwbEO8vVqthwQdnzE=
  app: stagingshalarelax
