language: java
jdk:
- openjdk8
dist: trusty
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: nzbvJTYZCq2tyGAmPMxIN0WX1b5Vvp0FlPRMEqJAnPzXh+WTmumsFANh7SH4FpVHP8d4YrvznKG/m4mhIDdleV56kunRq8SpkCzpm7/pSRugyzzqktYHjhwZxMDb8ZjlpDyIc6awwKL1Mqdhue97khKQke7kI82iHxawK3u+ZwSvyyL/cWMHZWi97K7DPQ0+tIgvfnml9HKXViENlXTrqWtI+2XbBv7sTyID+7nLgAsgSOGLoreX/oZVMP/9oLQlhtSVGToCWiFUi6nC2XFWyC3ftm6xSUIqGQBauYCw+K792IXPPWmQD4iSnbJ9OlMAQGCF8rkoAu8OLsogvnbBmy5/oQJma5EhddkXi3WT4lFLcB4zyyWysnHkOBDfD0GQQYoxDaWFkhgC6gtyaQzi/PuGavjC7zwe8fg10LrIu4s4T4H3Z901WmrlhEWfr4ASi9E734eX1jOuK9kVFy5ffUc8WUTgP1OsYM28lyjhuBwAKTlxUvwSszSrcv42APtMV0wqXD/6RaKOk13G8nrhnEdJPalIJB0b5gEFFr+ZvA3dXLBOXKw+TYoKn5Mn6igu/jVKnKBme/NK3nAzwjSVRJqNf7YBfhs09qrK/GCfGnW8zq7CT6VTPa04jaz778v70cseWNcrmny0JBdsZOMV/YMfkIoU9g/kH7yNwodSCfs=
  app: stagingshalarelax
