language: java
jdk:
- openjdk8
dist: trusty
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: UdzmZsf0taXTimF8Br0mVWmVPRQj0zWD2z8DCIOBi0uotGivZfuw/lkcWmmNiJm4Ypl2F5acoovUwZYpGxIrszls/pUW/kNu0HnlYqFlaIbuKXBmMbkMN/WWcaCuzHWVfm+RTQls4xm7qmAE3nZLWWY49+UnH6/gs5cHlUAO2CSJGgK8gcQaMX+7QR38y24i5mSs20TE2yBAj3Mo4N/ghqJpSRoipt2LExnJj8RigWQpUcBRpJlD4Di8UYOgmTtQXiYv9eVs6t4nw9J5+MplTiQnJZ5FSVAxwOS/EjbOW91Q4giYpz6ZnzC+L7emnZ4m6KTrDOv6259QdKJacOS27c0M+36tMq7lNzTG+tr+DiaxQtk5AZwLBEILP38DNXnnWoPGXda/JpgAFCklRJb1w285gJi14XovdrQv7jVApr10qoR1ujeyvPcZ+mM0rFTnRMnBOUwOghG67P/Ab/0c8oHq/BetQgtll9a2m0T3j4RJRVry9gLk4A0ALatmmRPqHSYkCmgz5PYE8oOZy0uvQi0LxOgStdm6p7VeqPCVkHoni+n196zjBuoLW2UgENqAuLUgrHfVu5xHs6bBVKXUi6KTgJ70ulvRoDek9GhApERgjESzg8xe7zHQs3potLdm4W/j+cuMQKKG8QQIy7rEAUlvA0cTiD7oVz2nYNeaE/Q=
  app: stagingshalarelax
