language: java
jdk:
- oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: VDj5cB4t9vT6ULESi8DIZ3i/bBZ7M8WRHzioeYN7K8RTIH2RQxVKIoGb4hA3+A1MMBjvIxOihLe8mi9UuVyOcrafuDClHkfqXYxk7Ig/ZgB3tC3S6KStwKvyPNGa8yI2e8GvQDD9N6IF47DE4uOFhBMgTG0NBexKhJXVQ/VvGtKTNqfse629dJb1lVbB9aJwUjHjJBJWFsDpP7x9AZaz4/mRUMpabcbEV1miJhqHyv9BtZZ/9ecehvcQ8HkrhhEFOfWvUhUcgXZDDs+JJR2VhoGwDb167SLN5woeNcr6zSg3uSPhG45dpeZQA0H+Ch6uDwPsIoV9WPrc/f+68jcybb6CaAPioQHeox4PNrNhv/wELzSsiA1E7RPzDESrC+sjoU/uqhbpmosXqCPkJG0Ry7QJt6JcXshnDvzwhadCVzYmnzP6/n7jiP5yyBnxxYXB30x/U14VVK32iDkTwzlch3qtTDgX4xmM9n1wgGlzp10gyFsnsYtD/Tntjafi0q5bZEWabmhi3PB+kAHVLfr+HOZTiKedIhbvKaJ80V9hFZkQYksaQuOwRZi8FIWwVZWArEGoGoCTQn7rgSRWMh9/7yC8lmqzRCCgKv1z4dTusWBEmoYSfntXzlr3lnWHrNJNH+MlDUNUmWaEOSTG0n7tkhfmcPkwa32AS77cQfHGeIQ=
  app: stagingshalarelax
