language: java
jdk:
- openjdk8
dist: trusty
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: ttGOvmMdXxjM4MQMOAh3bpu5hG5lBaQJbcs7wWSmczox9ciHnSZFCblvYfyDySLBZqB9RCjCs8rvkYLs31jfCfXZwYAJRDPrGvci8ocnl3oh1HwYAvysb48m233znKvWyuM+naMJdW6mnI9o49+dngoxBwygxJrEi81rIrzU31iNGhMVpuw7OcvYAu6S08loXCHK+FMhAApUKy9QGNdcpLZHTJVjyTVuxacShUjEbxlkSMDudcnIj7udYsqTcxOs3KNlkkGOOOBoXedmQ+5+nWUPLm7xXBAeuqEXDeX7OzWOu7IIXdLsJuPIE6ldBjnf3cjNzSMnH+METJUHaWtXNQeBWy7qM6Oc4m1okwDHre/uQ6Nd7Qb4cWpFm0klpGo1hRNgHN9TKaTFLa36nTDTK8YtQsRs5Rk2KkARMoFaSUqJKkod9x2Su0iRgM1yf9F3GivaOuDpfvzDC48dpvSiPpAhVJi1zIOETrvpRcY8nlxOEkjN95I8oydXOiRfiVcftiah+ud0N8Ap7YNN3JYOyu63JI9+Kvw1atwhx48STSDi2L//IgqSyO8kpGn47SBUEA1m1jUNzjOaohHlSZB3W4XKOh58e32UG/CV0JBPO9HIOx2Z6pZxWxXqboOHo69ITREiJLnBmuNLloq+uv4QkwUI1BnjNLEh49dG7uE9gMo=
  app: stagingshalarelax
